const mongoose = require("mongoose");

const CustomDesignSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    baseProductId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
      index: true,
    },

    // Shared body profile used for Studio and future 3D fitting.
    bodyProfileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BodyProfile",
      default: null,
      index: true,
    },

    baseItemType: {
      type: String,
      enum: [
        "top",
        "bottom",
        "dress",
        "shoes",
        "bag",
        "jewelry",
        "accessory",
        "outerwear",
      ],
      required: true,
      index: true,
    },

    title: {
      type: String,
      trim: true,
      maxlength: 150,
      default: "",
    },

    /*
     * Regular + advanced customization.
     *
     * Example:
     * color      = "Red"
     * pattern    = "Floral"
     * sleeveStyle = "Full"
     * neckDesign  = "V-Neck"
     * lengthType  = "Custom"
     * fit         = "Regular"
     * size        = "M"
     */
    attributes: {
      color: {
        type: String,
        trim: true,
        default: "",
      },

      pattern: {
        type: String,
        trim: true,
        default: "",
      },

      sleeveStyle: {
        type: String,
        trim: true,
        default: "",
      },

      neckDesign: {
        type: String,
        trim: true,
        default: "",
      },

      length: {
        type: String,
        trim: true,
        default: "",
      },

      lengthType: {
        type: String,
        trim: true,
        default: "",
      },

      fit: {
        type: String,
        trim: true,
        default: "",
      },

      size: {
        type: String,
        trim: true,
        default: "",
      },

      // For future visual/3D renderer parameters.
      customOptions: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
    },

    /*
     * Exact garment measurements when the user chooses
     * advanced/full customization.
     *
     * All numeric values use the unit stored below.
     */
    measurements: {
      unit: {
        type: String,
        enum: ["cm", "in"],
        default: "cm",
      },

      garmentLength: {
        type: Number,
        min: 0,
        default: null,
      },

      sleeveLength: {
        type: Number,
        min: 0,
        default: null,
      },

      neckDepth: {
        type: Number,
        min: 0,
        default: null,
      },

      shoulderWidth: {
        type: Number,
        min: 0,
        default: null,
      },

      chest: {
        type: Number,
        min: 0,
        default: null,
      },

      waist: {
        type: Number,
        min: 0,
        default: null,
      },

      hip: {
        type: Number,
        min: 0,
        default: null,
      },

      armhole: {
        type: Number,
        min: 0,
        default: null,
      },

      hemWidth: {
        type: Number,
        min: 0,
        default: null,
      },

      customMeasurements: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
      },
    },

    /*
     * Preview generated by the frontend/3D renderer.
     * This remains optional because the actual live renderer
     * will be implemented separately.
     */
    previewImageUrl: {
      type: String,
      trim: true,
      default: "",
    },

    /*
     * Server-controlled final price.
     * customDesignController sets this from the base product.
     */
    price: {
      type: Number,
      required: true,
      min: 0,
    },

    status: {
      type: String,
      enum: ["active", "deleted"],
      default: "active",
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

CustomDesignSchema.index({
  userId: 1,
  createdAt: -1,
});

CustomDesignSchema.index({
  userId: 1,
  status: 1,
  createdAt: -1,
});

module.exports = mongoose.model(
  "CustomDesign",
  CustomDesignSchema
);