const mongoose = require("mongoose");

const OUTFIT_ROLES = [
  "top",
  "bottom",
  "dress",
  "shoes",
  "bag",
  "jewelry",
  "accessory",
  "outerwear",
];

const OutfitItemSchema = new mongoose.Schema(
  {
    // Normal catalog product
    productId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      default: null,
    },

    // Custom garment created in Studio
    customDesignId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CustomDesign",
      default: null,
    },

    role: {
      type: String,
      enum: OUTFIT_ROLES,
      required: true,
      index: true,
    },

    selectedSize: {
      type: String,
      trim: true,
      default: "",
    },

    selectedColor: {
      type: String,
      trim: true,
      default: "",
    },
  },
  {
    _id: true,
  }
);

// Each item must be either a normal product OR a custom design.
OutfitItemSchema.pre("validate", function () {
  const hasProduct = !!this.productId;
  const hasCustomDesign = !!this.customDesignId;

  if (!hasProduct && !hasCustomDesign) {
    throw new Error(
      "Outfit item must have either productId or customDesignId"
    );
  }

  if (hasProduct && hasCustomDesign) {
    throw new Error(
      "Outfit item cannot have both productId and customDesignId"
    );
  }
});

const OutfitSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    name: {
      type: String,
      trim: true,
      maxlength: 150,
      default: "",
    },

    // Body profile used by Builder / future 3D fitting.
    bodyProfileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BodyProfile",
      default: null,
      index: true,
    },

    items: {
      type: [OutfitItemSchema],
      default: [],
    },

    // Preview generated by frontend / future 3D renderer.
    previewImageUrl: {
      type: String,
      trim: true,
      default: "",
    },

    // -----------------------------
    // Share Outfit
    // -----------------------------

    isPublic: {
      type: Boolean,
      default: false,
      index: true,
    },

    /*
     * IMPORTANT:
     * Do not store null as the default.
     *
     * A token exists only after the user shares
     * the outfit.
     */
    shareToken: {
      type: String,
      trim: true,
      default: undefined,
    },

    sharedAt: {
      type: Date,
      default: null,
    },

    status: {
      type: String,
      enum: ["active", "deleted"],
      default: "active",
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

// -----------------------------
// Normal indexes
// -----------------------------

OutfitSchema.index({
  userId: 1,
  createdAt: -1,
});

OutfitSchema.index({
  userId: 1,
  status: 1,
  createdAt: -1,
});

OutfitSchema.index({
  isPublic: 1,
  shareToken: 1,
});

// -----------------------------
// UNIQUE SHARE TOKEN
// -----------------------------

/*
 * Only real string tokens must be unique.
 *
 * Documents without a shareToken are allowed.
 * null / missing values are ignored.
 */
OutfitSchema.index(
  { shareToken: 1 },
  {
    name: "shareToken_unique_partial",
    unique: true,
    partialFilterExpression: {
      shareToken: {
        $type: "string",
      },
    },
  }
);

module.exports = mongoose.model(
  "Outfit",
  OutfitSchema
);